name: React CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '21'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Run Linter
      run: npm run lint
      continue-on-error: true

    - name: Build
      run: npm run build

    - name: Send failure email
      if: failure()

      uses: dawidd6/action-send-mail@v2
      with:

        server_address: smtp.gmail.com
        server_port: 465

        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: CI Failure in ${{ github.repository }}

        body: Build failed at ${{ github.ref }}
        to: ${{ secrets.EMAIL_RECEIVER }}
        from: ${{ secrets.EMAIL_SENDER }}

      env:
        SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt
